### PR TITLE
feat: add Jujutsu support

### PR DESCRIPTION
**Pull request by meskill**

### CODE REVIEW

**Review by azzamsa — COMMENTED** [review]
You need to update this line too.

**Review by azzamsa — CHANGES_REQUESTED** [review]
Take a look at the error in CI.

**Comment by meskill** [comment]
Ah, yes, I fixed this

**Comment by meskill** [comment]
@azzamsa please review

**Comment by azzamsa** [comment]
@meskill would you like to squash you commit to only contain `[add Jujutsu support](https://github.com/azzamsa/toor/pull/1/commits/676ef90cbab6302646ef02ca6cad4f6fbf7dd03f)` ?

**Comment by meskill** [comment]
> @meskill would you like to squash you commit to only contain `[add Jujutsu support](https://github.com/azzamsa/toor/pull/1/commits/676ef90cbab6302646ef02ca6cad4f6fbf7dd03f)` ?

You can enable squash merging in the repository settings and merge it the way you want

**Comment by azzamsa** [comment]
@meskill nice idea!

**Pull request merged**
